config/routes.rb
Rails.application.routes.draw do

  root :to =>'tops#index'

  get "tops/index" => "tops#index"

  resources :contacts

  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    collection do
        post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]

  resources :pictures do
      collection do
          post :confirm
      end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: { in: 1..140 }
  validates :image, presence: true
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length:{maximum: 30}
  validates :email, presence: true, length:{maximum: 80} ,format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save{email.downcase!}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture

  mount_uploader :icon_image, IconImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mailer(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(picture_id: params[:picture_id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:new, :show, :edit, :update, :destroy]

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  def index
    @pictures = Picture.all
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
      @picture.image.retrieve_from_cache! params[:cache][:image]
    else
      @picture = Picture.new
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"投稿を削除しました！"
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "投稿を編集しました！"
    else
      render 'edit'
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    @picture.image.retrieve_from_cache!  params[:cache][:image]
    if @picture.save
      redirect_to pictures_path, notice: "投稿しました！"
      NoticeMailer.notice_mailer(@picture).deliver
    else
      render 'new'
    end
  end

  private
    def picture_params
      params.require(:picture).permit(:title, :content, :image, :image_cache)
    end

    def set_picture
      @picture = Picture.find(params[:id])
    end

    def login_check
      if !current_user
        render("/sessions/new")
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render'new'
    end

  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user_infomation, only: [:edit, :update]

  def new
    if params[:back]
      @user = User.new(user_params)
      @user.icon_image.retrieve_from_cache! params[:cache][:icon_image]
    else
      @user = User.new
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  def show
    @user = User.find(params[:id])
    @favorites_pictures = @user.favorite_pictures.all
  end

  def create
    @user = User.new(user_params)
    @user.icon_image.retrieve_from_cache!  params[:cache][:image]
    if @user.save
      redirect_to new_session_path, notice:"新たにユーザー情報を登録しました！"
    else
      render'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報を編集しました！"
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon_image, :icon_image_cache)
    end

    def set_user_infomation
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path

    elsif action_name == 'edit'
      picture_path

    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
        confirm_users_path

    elsif action_name == 'edit'
        user_path

    end
  end
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Blog</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">InstagramClone</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/pictures">投稿一覧</a></li>
            <li><a href="/pictures/new">新規投稿</a></li>
            <li><a href="/contacts/new">お問い合わせ</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="login_tag"><%= link_to 'Profile', user_path(current_user.id) %></li>
              <li class="login_tag"><%= link_to 'Logout', session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li class="login_tag"><%= link_to "Sign up", new_user_path %></li>
              <li class="login_tag"><%= link_to "Login", new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>

    <footer>
      <p>2018年3月期生</p>
      <p>小山田湧亮</p>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="container">
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-warning" role="alert"><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li class="alert alert-warning" role="alert"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="picture_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="picture_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="picture_image">
    <p class="picture_image_lable"><%= form.label :image %></p>
    <p class="picture_image_input"><%= form.file_field :image, id: :@picture_image %></p>
    <%= image_tag(@picture.image.url) if @picture.image.url %>
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "投稿一覧画面にもどる", pictures_path %>
</div>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@picture.image.cache_name %>

  <p>タイトル:<%= @picture.title %></p>
  <p>本文:<%= @picture.content %></p>
  <p>
    <%= image_tag(@picture.image.url) %>
  </p>
  <%= form.submit  "投稿する" %>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@picture.image.cache_name %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>投稿を編集する</h2>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>

<table>
  <tr>
    <th class="index_picture_user_name">投稿者名</th>
    <th class="index_picture_title">タイトル</th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td class="index_picture"><%= picture.user.name%></td>
    <td class="index_picture"><%= link_to picture.title , picture_path(picture.id), class: 'btn btn-info' %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to '投稿する', new_picture_path %>

app/views/pictures/new.html.erb
<h2>投稿する</h2>

<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>

<p class="show_picture_user_name">投稿者名: <%= @picture.user.name %></p>
<p class="show_picture_image">
  <%= image_tag @picture.image %>
</p>
<p class="show_picture_title">タイトル: <%= @picture.title %></p>
<p class="show_picture_content">内容: <%= @picture.content %></p>
<% if @picture.user == current_user %>
  <p class="show_picture_edit"><%= link_to '編集', edit_picture_path(@picture.id), class: 'btn btn-warning' %></p>
  <p class="show_picture_delete"><%= link_to '削除', picture_path(@picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' } , class: 'btn btn-danger'%></p>
<% end %>

<% unless @picture.user == current_user %>
  <% if @favorite.present? %>
    <div class="favorites_cancelled">
      <%= link_to 'お気に入り解除する', favorite_path(picture_id: @picture.id), method: :delete, class: 'btn btn-danger' %>
    </div>
  <% else %>
    <div class="favorites">
      <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

<br>

<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/tops/index.html.erb
<section class="main-header">
  <img src="/images/instagram05.png">
</section>

<section class="row about">
  <h1>About InstagramClone</h1>
  <p>
    InstagramCloneは、日常の出来事を写真と共に共有できるアプリです。<br>
    言葉ではなく写真だからこそ伝わるものがあると思います。
  </p>
</section>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, url: user_choose_new_or_edit) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-warning" role="alert"><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li class="alert alert-warning" role="alert"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="user_email">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="user_password">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="user_password_confirmation">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="new_icon">
    <p class="new_icon_lable"><%= form.label :icon_image %></p>
    <p class="new_icon_image"><%= form.file_field :icon_image, id: :@user_icon_image %></p>
    <%= image_tag(@user.icon_image.url) if @user.icon_image.url %>
    <%= form.hidden_field :icon_image_cache %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "ユーザー詳細画面にもどる", user_path(@user.id) %>

app/views/users/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= form.hidden_field :password %>
  <%= form.hidden_field :password_confirmation %>
  <%= hidden_field_tag :"cache[image]",@user.icon_image.cache_name %>

  <p>名前:<%= @user.name %></p>
  <p>メールアドレス:<%= @user.email %></p>
  <p>パスワード:<%= @user.password %></p>
  <p>
    <%= image_tag(@user.icon_image.url) %>
  </p>
  <%= form.submit "登録する" %>
<% end %>

<%= form_with(model:@user, url:new_user_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= hidden_field_tag :"cache[icon_image]",@user.icon_image.cache_name %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/users/edit.html.erb
<h2>ユーザー情報を編集する</h2>

<%= render 'form' %>

app/views/users/new.html.erb
<div class="container">

<h1>Sign up</h1>

<%= form_with(model: @user, local: true, url:confirm_users_path) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-warning" role="alert"><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li class="alert alert-warning" role="alert"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="user_email">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="user_password">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="user_password_confirmation">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="new_icon">
    <p class="new_icon_lable"><%= form.label :icon_image %></p>
    <p class="new_icon_image"><%= form.file_field :icon_image, id: :@user_icon_image %></p>
    <%= image_tag(@user.icon_image.url) if @user.icon_image.url %>
    <%= form.hidden_field :icon_image_cache %>
  </div>

  <%= form.submit "Create my account" %>

<% end %>
</div>

app/views/users/show.html.erb
<h4 class="user_infomation"><%= @user.name %>のページ</h4>
<p class="user_infomation_image">
  <%= image_tag @user.icon_image %>
</p>
<p class="user_infomation">メールアドレス: <%= @user.email %></p>
<p class="user_infomation">
  <%= link_to 'ユーザー情報を編集', edit_user_path(@user.id), class: 'btn btn-warning' %>
</p>

<div class="container">
  <h1>お気に入り投稿一覧</h1>

  <table>
    <tr>
      <th class="index_favorite_picture_user_name">投稿者名</th>
      <th class="index_favorite_picture_title">タイトル</th>
      <th class="index_favorite_picture_content">内容</th>
      <th class="index_favorite_picture_content">image</th>
    </tr>

  <% if !@favorites_pictures.nil? %>
    <% @favorites_pictures.each do |favorites_picture| %>
      <tr>
        <td class="index_favorite_picture"><%= favorites_picture.user.name %></td>
        <td class="index_favorite_picture"><%= favorites_picture.title %></td>
        <td class="index_favorite_picture"><%= favorites_picture.content %></td>
        <td class="index_favorite_picture_image">
          <%= image_tag favorites_picture.image %>
        </td>
      </tr>
    <% end %>
  <% end %>

  </table>
</div>